CREATE TABLE item
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    upload_flag BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_item PRIMARY KEY (id)
);